### ISSUE TITLE
Typo in "Tuning the XML server running in a pod" section

### ISSUE THREAD

**Issue by khippsley** [IBM/spm-performance-tuning#6]
There is a typo here: https://ibm.github.io/spm-performance-tuning/openshift/tune_xmlserver/tune_xmlserver#tuning-the-xml-server-running-in-a-pod

This sentence ends abruptly: "The [Deploying Helm charts] section describes how to specify Helm chart overrides in its ."

**Comment by khippsley** [comment]
This is in version v22.1.0

**Comment by wwwild** [comment]
Proposed text change is to change the "... its ." to "... an override file." as that fits best the context of the external Runbook page that sentence references.

**Comment by wwwild** [comment]
This has been corrected in the [April 2022 release](https://github.com/IBM/spm-performance-tuning/releases/tag/22.4.0) of the [Tuning Guide](https://ibm.github.io/spm-performance-tuning/).
